name: i18n.core

on: push

env:
  GITVERSION_VERSION: 5.3.4
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1 

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Fetch all history for all tags and branches (gitversion requirement)
        run: git fetch --prune --unshallow
                      
      - name: Read dotnet sdk version from global.json
        shell: pwsh
        run: |
          $DOTNET_VERSION = Get-Content ".\${{ env.GITHUB_WORKSPACE }}\global.json" | ConvertFrom-Json | Select-Object -Expand sdk | Select-Object -Expand version    
          echo "::set-env name=DOTNET_VERSION::$DOTNET_VERSION"
          
      - name: Setup dotnet v${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - id: set-version
        name: Setup GitVersion v${{ env.GITVERSION_VERSION }} 
        shell: pwsh
        run: |
          dotnet tool update GitVersion.Tool --global --version ${{ env.GITVERSION_VERSION }}
          $BUILD_VERSION = (dotnet gitversion /showVariable NugetVersionv2) | out-string
          echo "::set-env name=BUILD_VERSION::$BUILD_VERSION"
                
      - name: Build
        shell: pwsh
        run: |
          pwsh -c ".\${{ env.GITHUB_WORKSPACE }}\build.ps1" -Target Build -Version ${{ env.BUILD_VERSION }} -Nupkg -CI
          echo "${{ env.BUILD_VERSION }}" | Out-File ".\${{ env.GITHUB_WORKSPACE }}\nupkgs\nupkg_version.txt"

      - name: Test pot tool v${{ env.BUILD_VERSION }}
        shell: pwsh
        run: pwsh -c ".\${{ env.GITHUB_WORKSPACE }}\build.ps1" -Target Test-Pot -Version ${{ env.BUILD_VERSION }} -CI
        
      - name: Upload nupkg
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: nupkgs-${{ matrix.os }}
          path: ${{ github.workspace }}/nupkgs/**/*
        
  publish:
     if: success()
     runs-on: ubuntu-latest
     name: Publish nuget packages
     needs: [build]
     steps:
      
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Download nupkgs
        uses: actions/download-artifact@v2
        with:
          name: nupkgs-windows-latest
          path: ${{ github.workspace }}/nupkgs
          
      - name: Push nuget packages 
        shell: pwsh
        run: | 
          $nupkg_version = Get-Content ".\${{ env.GITHUB_WORKSPACE }}\nupkgs\nupkg_version.txt"
          pwsh -c ".\${{ env.GITHUB_WORKSPACE }}\build.ps1" -Target Nupkg-Push -Version $nupkg_version -CI -NupkgApiKey ${{ secrets.PETERSUNDE_NUGET_ORG_API_KEY }}
          echo "::set-env name=NUPKG_VERSION::$nupkg_version"
            
      - name: Create github release tag
        if: success() && github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NUPKG_VERSION }}
          release_name: Release v${{ env.NUPKG_VERSION }}
          draft: true
          prerelease: false
